//! Generation of the commented `config.toml` written by `st config init`.
//!
//! The document is produced *from a real [`Config`] value*, so it can never
//! describe a default the code does not have: the value of every key is
//! serialised from the struct, and a test asserts that the comment table below
//! covers exactly the keys the struct serialises.

use crate::error::ConfigError;
use crate::Config;

/// One documented key inside a section.
struct Key {
    /// The key name as it appears in TOML.
    name: &'static str,
    /// Comment lines emitted above the key (without the leading `# `).
    doc: &'static [&'static str],
    /// Rendered as a commented-out line when the key is absent from the
    /// serialised document (an unset `Option`).
    absent: Option<&'static str>,
}

/// One `[section]` of the generated document.
struct Section {
    /// Dotted path into the serialised document (`"window.padding"`).
    path: &'static str,
    /// Comment lines emitted above the `[section]` header.
    doc: &'static [&'static str],
    /// Keys in emission order. Ignored when `dynamic` is set.
    keys: &'static [Key],
    /// Emit every key found in the table instead of `keys` (for free-form maps).
    dynamic: bool,
    /// Extra literal lines (already comment-prefixed) emitted after the keys.
    trailer: &'static [&'static str],
}

const fn key(name: &'static str, doc: &'static [&'static str]) -> Key {
    Key {
        name,
        doc,
        absent: None,
    }
}

const fn opt_key(name: &'static str, doc: &'static [&'static str], absent: &'static str) -> Key {
    Key {
        name,
        doc,
        absent: Some(absent),
    }
}

const fn section(
    path: &'static str,
    doc: &'static [&'static str],
    keys: &'static [Key],
) -> Section {
    Section {
        path,
        doc,
        keys,
        dynamic: false,
        trailer: &[],
    }
}

const HEADER: &[&str] = &[
    "superterminal configuration",
    "",
    "Location (first match wins):",
    "  $SUPERTERMINAL_CONFIG",
    "  $XDG_CONFIG_HOME/superterminal/config.toml",
    "  ~/.config/superterminal/config.toml                        (Linux)",
    "  ~/Library/Application Support/superterminal/config.toml    (macOS)",
    "",
    "Every section and every key is optional; anything missing falls back to",
    "the value shown here. Unknown keys are ignored with a warning. The file is",
    "read once at startup by both `superterminald` and the client - there is no",
    "hot reload yet.",
    "",
    "This file is generated by `st config init`; it lists the defaults.",
];

const SECTIONS: &[Section] = &[
    section(
        "font",
        &["The monospaced family used for terminal cells."],
        &[
            opt_key(
                "family",
                &[
                    "Family name. Unset means the platform default:",
                    "\"Menlo\" on macOS, \"DejaVu Sans Mono\" on Linux.",
                ],
                "family = \"JetBrains Mono\"",
            ),
            key("size", &["Font size in pixels."]),
            key(
                "line_height",
                &["Cell height as a multiple of the font size."],
            ),
        ],
    ),
    section(
        "window",
        &["Window chrome and compositing."],
        &[
            key(
                "background",
                &[
                    "\"auto\" | \"blurred\" | \"transparent\" | \"opaque\".",
                    "\"auto\" resolves to \"blurred\" on macOS and \"opaque\" on Linux;",
                    "\"blurred\" behaves as \"transparent\" on Linux (no blur there).",
                ],
            ),
            key(
                "vertical_tabs",
                &["Put the tab strip down the left edge instead of along the top."],
            ),
        ],
    ),
    section(
        "window.padding",
        &[
            "Pixels between the window edge and the cell grid.",
            "The scrollbar is drawn inside the right padding.",
        ],
        &[
            key("top", &[]),
            key("right", &[]),
            key("bottom", &[]),
            key("left", &[]),
        ],
    ),
    section(
        "shell",
        &["What the server spawns in a new Surface."],
        &[
            opt_key(
                "program",
                &["Unset means $SHELL, then /bin/sh."],
                "program = \"/usr/bin/fish\"",
            ),
            key(
                "args",
                &["Arguments passed to the program, before the login flag."],
            ),
            opt_key(
                "login",
                &[
                    "Start as a login shell. `-l` is appended for bash, zsh and fish",
                    "only. Unset means the platform default: true on macOS,",
                    "false on Linux.",
                ],
                "login = true",
            ),
        ],
    ),
    section(
        "terminal",
        &["Emulation and interaction."],
        &[
            key(
                "scrollback_lines",
                &["Lines of history per Surface. Clamped to 100000."],
            ),
            key(
                "bold_is_bright",
                &["Draw bold text in indexed colours 0-7 with colours 8-15."],
            ),
            key(
                "alt_screen_scroll",
                &[
                    "Send arrow keys for wheel events on the alternate screen,",
                    "so pagers such as `less` scroll.",
                ],
            ),
            key(
                "word_chars",
                &[
                    "Characters that count as part of a word, in addition to",
                    "letters and digits, when double-clicking to select.",
                ],
            ),
            key(
                "option_as_alt",
                &[
                    "macOS only: \"none\" | \"left\" | \"right\" | \"both\".",
                    "Anything but \"none\" makes Option prefix ESC instead of",
                    "composing characters.",
                ],
            ),
            key(
                "backspace_sends",
                &["\"del\" sends 0x7F (xterm default), \"bs\" sends 0x08 (^H)."],
            ),
        ],
    ),
    section(
        "theme",
        &[
            "Terminal palette. Every value is a hex colour (\"#rrggbb\", or the",
            "short \"#rgb\"). The server reads this section too, to answer OSC 10",
            "and OSC 11 colour queries.",
        ],
        &[
            key("foreground", &["Default text colour (OSC 10)."]),
            key("background", &["Default background colour (OSC 11)."]),
            key("cursor", &["Cursor block."]),
            key("cursor_text", &["Character underneath a block cursor."]),
            key("selection_background", &["Background of selected cells."]),
            key("selection_foreground", &["Foreground of selected cells."]),
            key("black", &["", "The 16 ANSI colours, indexes 0-15."]),
            key("red", &[]),
            key("green", &[]),
            key("yellow", &[]),
            key("blue", &[]),
            key("magenta", &[]),
            key("cyan", &[]),
            key("white", &[]),
            key("bright_black", &[]),
            key("bright_red", &[]),
            key("bright_green", &[]),
            key("bright_yellow", &[]),
            key("bright_blue", &[]),
            key("bright_magenta", &[]),
            key("bright_cyan", &[]),
            key("bright_white", &[]),
        ],
    ),
    Section {
        path: "keybindings",
        doc: &[
            "Shortcut overrides, `command id = \"shortcut\"`. Only the commands you",
            "list are changed; everything else keeps its built-in binding.",
            "`mod` is Cmd on macOS and Ctrl+Shift on Linux.",
            "",
            "Command ids: app.quit, app.reconnect, edit.copy, edit.paste,",
            "palette.commands, session.new, session.rename, session.switch,",
            "surface.clearScrollback, tab.close, tab.goto.1 .. tab.goto.9,",
            "tab.new, tab.next, tab.prev, view.toggleVerticalTabs.",
        ],
        keys: &[],
        dynamic: true,
        trailer: &[
            "# \"tab.new\" = \"mod+t\"",
            "# \"palette.commands\" = \"mod+shift+p\"",
        ],
    },
    section(
        "server",
        &["The background server (`superterminald`)."],
        &[
            key(
                "idle_exit_minutes",
                &[
                    "Exit after this many minutes with no clients connected and no",
                    "Surface doing work. 0 disables idle exit.",
                ],
            ),
            key(
                "osc52",
                &["Let programs write the clipboard with OSC 52. Off in v1."],
            ),
        ],
    ),
];

/// Renders the fully commented document for `config`.
pub(crate) fn render(config: &Config) -> Result<String, ConfigError> {
    let doc = toml::Table::try_from(config)?;
    let mut out = String::with_capacity(4096);

    for line in HEADER {
        push_comment(&mut out, line);
    }

    for sec in SECTIONS {
        out.push('\n');
        for line in sec.doc {
            push_comment(&mut out, line);
        }
        out.push('[');
        out.push_str(sec.path);
        out.push_str("]\n");

        let table = lookup(&doc, sec.path);

        if sec.dynamic {
            if let Some(table) = table {
                for (name, value) in table {
                    out.push_str(&render_pair(name, value)?);
                }
            }
        } else {
            for k in sec.keys {
                let value = table.and_then(|t| t.get(k.name));
                match (value, k.absent) {
                    (Some(value), _) => {
                        push_key_doc(&mut out, k.doc);
                        out.push_str(&render_pair(k.name, value)?);
                    }
                    (None, Some(absent)) => {
                        push_key_doc(&mut out, k.doc);
                        out.push_str("# ");
                        out.push_str(absent);
                        out.push('\n');
                    }
                    (None, None) => {
                        return Err(ConfigError::Serialize(missing_key(sec.path, k.name)));
                    }
                }
            }
        }

        for line in sec.trailer {
            out.push_str(line);
            out.push('\n');
        }
    }

    Ok(out)
}

/// Builds the `toml::ser::Error` used when the comment table and the struct
/// have drifted apart. Only reachable through a programming mistake, which the
/// `covers_every_serialised_key` test catches first.
fn missing_key(section: &str, key: &str) -> toml::ser::Error {
    serde::ser::Error::custom(format!(
        "config example template lists `{section}.{key}`, which the schema does not serialise"
    ))
}

/// Emits a key's comment block. An empty line becomes a real blank line, which
/// separates groups of keys inside one section.
fn push_key_doc(out: &mut String, doc: &[&str]) {
    for line in doc {
        if line.is_empty() {
            out.push('\n');
        } else {
            push_comment(out, line);
        }
    }
}

fn push_comment(out: &mut String, line: &str) {
    if line.is_empty() {
        out.push_str("#\n");
    } else {
        out.push_str("# ");
        out.push_str(line);
        out.push('\n');
    }
}

/// Formats `name = value` by asking the TOML serialiser, so quoting and
/// escaping are never hand-rolled.
fn render_pair(name: &str, value: &toml::Value) -> Result<String, ConfigError> {
    let mut one = toml::Table::new();
    one.insert(name.to_owned(), value.clone());
    Ok(toml::to_string(&one)?)
}

/// Walks a dotted path into a table.
fn lookup<'a>(doc: &'a toml::Table, path: &str) -> Option<&'a toml::Table> {
    let mut current = doc;
    for part in path.split('.') {
        current = current.get(part)?.as_table()?;
    }
    Some(current)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    /// Collects the dotted path of every scalar in the document.
    fn leaf_paths(value: &toml::Value, prefix: &str, out: &mut BTreeSet<String>) {
        match value {
            toml::Value::Table(t) => {
                for (k, v) in t {
                    let path = if prefix.is_empty() {
                        k.clone()
                    } else {
                        format!("{prefix}.{k}")
                    };
                    leaf_paths(v, &path, out);
                }
            }
            _ => {
                out.insert(prefix.to_owned());
            }
        }
    }

    #[test]
    fn covers_every_serialised_key() {
        let doc = toml::Value::Table(toml::Table::try_from(Config::default()).unwrap());
        let mut actual = BTreeSet::new();
        leaf_paths(&doc, "", &mut actual);

        let mut templated = BTreeSet::new();
        for sec in SECTIONS {
            if sec.dynamic {
                continue;
            }
            for k in sec.keys {
                templated.insert(format!("{}.{}", sec.path, k.name));
            }
        }
        // Optional keys are absent from a default document but templated.
        let optional: BTreeSet<String> = SECTIONS
            .iter()
            .flat_map(|s| {
                s.keys
                    .iter()
                    .filter(|k| k.absent.is_some())
                    .map(move |k| format!("{}.{}", s.path, k.name))
            })
            .collect();

        assert_eq!(
            &templated - &optional,
            actual,
            "docs/config-example.toml template is out of sync with the schema"
        );
    }

    #[test]
    fn sections_are_unique_and_ordered_parents_first() {
        let mut seen: Vec<&str> = Vec::new();
        for sec in SECTIONS {
            assert!(!seen.contains(&sec.path), "duplicate section {}", sec.path);
            if let Some((parent, _)) = sec.path.rsplit_once('.') {
                assert!(
                    seen.contains(&parent),
                    "{} must come after [{parent}]",
                    sec.path
                );
            }
            seen.push(sec.path);
        }
    }
}
